name: ci_cd
on:
  push:
    branches:
      - main
  pull_request:
    branches:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
      steps:
        - uses: actions/checkout@v3
        - name: Install dependencies
          run: |
            pip install -e ".['dev']"
        - name:
          run: |
            ruff check .
